### ISSUE TITLE
Version number v1.3.1 not set correctly

### ISSUE THREAD

**Issue by eric2905** [inventwo/ioBroker.vis-inventwo#32] opened 2020-04-09 19:21 UTC
The current update to v1.3.1 didn't set it's internal version number correct.
It still shows v1.3.0 ... so it keeps updatable ..... endless loop.

**Comment by eric2905** [comment] 2020-04-10 05:20
Additional info - found in log after update

host.iobroker | 2020-04-10 07:18:06.430 | info | iobroker exit 0
-- | -- | -- | --
host.iobroker | 2020-04-10 07:18:05.434 | error | iobroker Cannot find io-package.json in "null": Error: ENOENT: no such file or directory, open 'null/io-package.json'
host.iobroker | 2020-04-10 07:18:04.411 | info | iobroker upgrade vis-inventwo

**Comment by skvarel** [comment] 2020-04-10 08:46
We have some add. questions to localize this problem.

• Which version of js-controller do you use?
• Which OS do you use?
• Update about Admin Panel or about GitHub?

We tested the adapter on various systems. The update to 1.3.1 worked everywhere.

We are currently checking the io-package.json and package.json and will then contact you again.

**Comment by skvarel** [comment] 2020-04-10 08:47
> 
> 
> Additional info - found in log after update
> host.iobroker 	2020-04-10 07:18:06.430 	info 	iobroker exit 0
> host.iobroker 	2020-04-10 07:18:05.434 	error 	iobroker Cannot find io-package.json in "null": Error: ENOENT: no such file or directory, open 'null/io-package.json'
> host.iobroker 	2020-04-10 07:18:04.411 	info 	iobroker upgrade vis-inventwo

**Comment by eric2905** [comment] 2020-04-10 08:54
Controller : 3.0.4 (See [here](https://forum.iobroker.net/topic/32036/beta-test-js-controller-3-0-x-auf-github) )
OS : Ubuntu 18.04.4 LTS
Update : Via Admin

**Comment by jkvarel** [comment] 2020-04-10 09:04
You are the second person we kown that is using the beta version of the controller and getting the error. After some research in the internet the problem could be a beta version of the controller or npm.  The threads are 2-3 years old but the current betas maybe have the problem again.

https://github.com/ioBroker/ioBroker.javascript/issues/231
https://forum.iobroker.net/topic/4377/error-enoent-bei-installation/2

**Comment by jkvarel** [comment] 2020-04-10 09:08
I checked the package-lock.json and saw that the version is still on 1.3.0. Could this be the problem. I will push an update to vrsion 1.3.2

**Comment by eric2905** [comment] 2020-04-10 09:26
Just installed v1.3.2 from Git.
Version is shown correct now.

**Comment by jkvarel** [comment] 2020-04-10 10:01
Great. I hope the problem is fixed now. If not please let us know

**Closed** 2020-04-19 10:34 UTC
